echo ""
echo ""
echo ""
echo "  _    _  _            ____   ___  _ "
echo " | |  | || | _____   _/ ___| / _ \| |"
echo " | |  | || ||_  / | | \___ \| | | | |"
echo " | |__|__   _/ /| |_| |___) | |_| | |___"
echo " |_____| |_|/___|\__, |____/ \__\_\_____|"
echo "                  |___/     "
echo ""
echo ""
echo ""
echo "    Let's Make Your Exploitation And Have Fun"
echo "" 
echo "    ==[ Tools Name : Tool-X"
echo "    ==[ Coded by : User-X"
echo "    ==[ Version : 1.0"
echo "    ==[ Codename : Tool-X"
echo ""
echo "-------------------"
echo ""
echo "---------------------------"
echo "DISCLAIMER | READ IT FIRST"
echo "---------------------------"
echo ""
echo "Using And Installing This Tools That Mean You Ready For"
echo ""
echo "[1] Use At Your Own Risk"
echo "[2] No Warranty"
echo "[3] If it violates the law with this tool the risk is borne by the user"
echo ""
echo "-------------------------------------------"
echo "Are You Sure Want To Install w3m"
echo "-------------------------------------------"
echo ""
echo "Press Enter if you Agree / Continue Install"
echo "Press CTRL + C if you Disagree / Cancel Install"
read ENTER
echo ""
echo ""
echo "Installing w3m"
pkg install w3m
echo ""
echo "type w3m from your terminal command if you wanna start using w3m"
echo ""

